[package]
name = "renderer_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
headless_chrome = "1.0.10"
warp = "0.3.7"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
